# Generated by Django 3.1.5 on 2021-02-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=12)),
                ('chatik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatik', to='chat.chats')),
            ],
        ),
    ]
