# Generated by Django 3.1.5 on 2021-02-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
    ]
