# Generated by Django 3.1.5 on 2021-02-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default='some string', on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.chats'),
        ),
    ]
